name: DevOps EFT Pipeline Complete

on:
  push:
    branches: [ main ]

jobs:
  # ETAPA 1: Calidad y Seguridad
  quality-and-security:
    name: Code Quality & Security Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar Pruebas
        run: |
          cd vote
          pip install pytest
          pytest

  # ETAPA 2: Construcción y Publicación en GHCR
  build-and-push:
    name: Container Build & Push to GHCR
    needs: quality-and-security
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          push: true
          # El nombre de la imagen debe estar en minúsculas por norma de Docker
          tags: ghcr.io/${{ github.repository_owner }}/vote:latest

  # ETAPA 3: Despliegue en Kubernetes (Simulado)
  deploy:
    name: Kubernetes Orchestration
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simular Despliegue en K8s
        run: |
          echo "Conectando al cluster..."
          echo "Desplegando imagen desde ghcr.io/${{ github.repository_owner }}/vote:latest"
          echo "Despliegue finalizado exitosamente."
